version: '3.7'

services:
  web:
    image: ghcr.io/implodium/implo-place/web
    build: web
    depends_on: [server]
    container_name: implo-places-web
    ports:
      - "80:80"

  server:
    image: ghcr.io/implodium/implo-place/server
    build: server
    restart: always
    container_name: implo-places-server
    ports:
      - "8080:8080"

  database:
    image: postgres
    container_name: implo-place-database
    privileged: true
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
      - ./data/:/var/lib/postgresql/data